name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  upload:
    uses: ./.github/workflows/create-upload.yaml
    with:
      container: docker-insert-app
    secrets: inherit
